{
 "title": "Jmeter Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Response Count with Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jmeter_count_total", "legendFormat": "{{code}}" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jmeter_rt_summary", "legendFormat": "Quantile {{quantile}}" }
   ]
  },
  {
   "title": "Jmeter Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jmeter_threads", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Samples(OK/Failed)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_success_ratio_success) by (label)",
     "legendFormat": "OK"
    },
    { "expr": "jmeter_failure_total", "legendFormat": "FAILED" }
   ]
  }
 ]
}